### ISSUE TITLE
Add TShirt size field to tasks

### ISSUE THREAD

**Issue by afederici75** [afederici75/Videomatic#30]
TO better orchestrate estimates all tasks need a size estimate

Sizes Here
https://www.c-sharpcorner.com/article/agile-story-point-estimation-techniques-t-shirt-sizing/#:~:text=What%20is%20T%2Dshirt%20sizing,%2C%20M%2C%20L%2C%20XL.

**Action Items**
-Add new single-select field to Github 
 - [ ] S - Small
 - [ ] M - Medium
 - [ ] L - Large
 - [ ] XL - Extra Large
-Pick nice colors for each of the above

**Comment by afederici75** [comment]
Comment 1

**Comment by afederici75** [comment]
Comment 2

**Comment by afederici75** [comment]
Completed with style

**Comment by enmcewan** [comment]
This is the end
